import type { VerifiedContentBatch } from './catalog.ts';
import type { Question } from '../domain/types.ts';

/**
 * Editorially reviewed capital/country claims.
 *
 * Each row is one independent country → capital relation.  The country
 * entity URL is deliberately kept on the question provenance so a future
 * catalogue builder can re-check the capital (P36) claim instead of treating
 * this file as an opaque generated list.  Wikidata item data is CC0; the
 * checked date and method below make the review reproducible.
 */
const checkedAt = '2026-09-15';
const source = 'Wikidata country entities (capital, P36)';
const license = 'CC0 1.0 Universal';
const method = 'Relecture éditoriale du libellé français et du claim P36 sur l’entité pays; une relation distincte par État; aucune variante générée.';

type CapitalRow = readonly [iso: string, country: string, capital: string, wikidataId: string];

const rows: readonly CapitalRow[] = [
  ['AF', 'Afghanistan', 'Kaboul', 'Q889'],
  ['AL', 'Albanie', 'Tirana', 'Q222'],
  ['DZ', 'Algérie', 'Alger', 'Q262'],
  ['AD', 'Andorre', 'Andorre-la-Vieille', 'Q228'],
  ['AO', 'Angola', 'Luanda', 'Q916'],
  ['AG', 'Antigua-et-Barbuda', 'Saint John’s', 'Q781'],
  ['AR', 'Argentine', 'Buenos Aires', 'Q414'],
  ['AM', 'Arménie', 'Erevan', 'Q399'],
  ['AT', 'Autriche', 'Vienne', 'Q40'],
  ['AZ', 'Azerbaïdjan', 'Bakou', 'Q227'],
  ['BS', 'Bahamas', 'Nassau', 'Q778'],
  ['BH', 'Bahreïn', 'Manama', 'Q398'],
  ['BD', 'Bangladesh', 'Dacca', 'Q902'],
  ['BB', 'Barbade', 'Bridgetown', 'Q244'],
  ['BY', 'Biélorussie', 'Minsk', 'Q184'],
  ['BE', 'Belgique', 'Bruxelles', 'Q31'],
  ['BZ', 'Belize', 'Belmopan', 'Q242'],
  ['BJ', 'Bénin', 'Porto-Novo', 'Q962'],
  ['BT', 'Bhoutan', 'Thimphou', 'Q917'],
  ['BW', 'Botswana', 'Gaborone', 'Q963'],
  ['BN', 'Brunei', 'Bandar Seri Begawan', 'Q921'],
  ['BG', 'Bulgarie', 'Sofia', 'Q219'],
  ['BF', 'Burkina Faso', 'Ouagadougou', 'Q965'],
  ['BI', 'Burundi', 'Gitega', 'Q967'],
  ['KH', 'Cambodge', 'Phnom Penh', 'Q424'],
  ['CM', 'Cameroun', 'Yaoundé', 'Q1009'],
  ['CV', 'Cabo Verde', 'Praia', 'Q1011'],
  ['TD', 'Tchad', 'N’Djamena', 'Q657'],
  ['CL', 'Chili', 'Santiago', 'Q298'],
  ['CN', 'Chine', 'Pékin', 'Q148'],
  ['CO', 'Colombie', 'Bogotá', 'Q739'],
  ['KM', 'Comores', 'Moroni', 'Q970'],
  ['CG', 'République du Congo', 'Brazzaville', 'Q971'],
  ['CR', 'Costa Rica', 'San José', 'Q800'],
  ['HR', 'Croatie', 'Zagreb', 'Q224'],
  ['CU', 'Cuba', 'La Havane', 'Q241'],
  ['CY', 'Chypre', 'Nicosie', 'Q229'],
  ['CZ', 'Tchéquie', 'Prague', 'Q213'],
  ['DK', 'Danemark', 'Copenhague', 'Q35'],
  ['DJ', 'Djibouti', 'Djibouti', 'Q977'],
  ['DM', 'Dominique', 'Roseau', 'Q784'],
  ['DO', 'République dominicaine', 'Saint-Domingue', 'Q786'],
  ['EC', 'Équateur', 'Quito', 'Q736'],
  ['EG', 'Égypte', 'Le Caire', 'Q79'],
  ['SV', 'Salvador', 'San Salvador', 'Q792'],
  ['ER', 'Érythrée', 'Asmara', 'Q986'],
  ['EE', 'Estonie', 'Tallinn', 'Q191'],
  ['ET', 'Éthiopie', 'Addis-Abeba', 'Q115'],
  ['FJ', 'Fidji', 'Suva', 'Q712'],
  ['FI', 'Finlande', 'Helsinki', 'Q33'],
  ['FR', 'France', 'Paris', 'Q142'],
  ['GA', 'Gabon', 'Libreville', 'Q1000'],
  ['GM', 'Gambie', 'Banjul', 'Q1005'],
  ['GE', 'Géorgie', 'Tbilissi', 'Q230'],
  ['DE', 'Allemagne', 'Berlin', 'Q183'],
  ['GH', 'Ghana', 'Accra', 'Q117'],
  ['GR', 'Grèce', 'Athènes', 'Q41'],
  ['GD', 'Grenade', 'Saint-Georges', 'Q769'],
  ['GT', 'Guatemala', 'Guatemala', 'Q774'],
  ['GN', 'Guinée', 'Conakry', 'Q1006'],
  ['GW', 'Guinée-Bissau', 'Bissau', 'Q1007'],
  ['GY', 'Guyana', 'Georgetown', 'Q734'],
  ['HT', 'Haïti', 'Port-au-Prince', 'Q790'],
  ['HN', 'Honduras', 'Tegucigalpa', 'Q783'],
  ['HU', 'Hongrie', 'Budapest', 'Q28'],
  ['IS', 'Islande', 'Reykjavik', 'Q189'],
  ['IN', 'Inde', 'New Delhi', 'Q668'],
  ['IR', 'Iran', 'Téhéran', 'Q794'],
  ['IQ', 'Irak', 'Bagdad', 'Q796'],
  ['IE', 'Irlande', 'Dublin', 'Q27'],
  ['IT', 'Italie', 'Rome', 'Q38'],
  ['JM', 'Jamaïque', 'Kingston', 'Q766'],
  ['JO', 'Jordanie', 'Amman', 'Q810'],
  ['KZ', 'Kazakhstan', 'Astana', 'Q232'],
  ['KE', 'Kenya', 'Nairobi', 'Q114'],
  ['KI', 'Kiribati', 'Tarawa-Sud', 'Q710'],
  ['KW', 'Koweït', 'Koweït', 'Q817'],
  ['KG', 'Kirghizistan', 'Bichkek', 'Q813'],
  ['LA', 'Laos', 'Vientiane', 'Q819'],
  ['LV', 'Lettonie', 'Riga', 'Q211'],
  ['LB', 'Liban', 'Beyrouth', 'Q822'],
  ['LR', 'Liberia', 'Monrovia', 'Q1014'],
  ['LY', 'Libye', 'Tripoli', 'Q1016'],
  ['LI', 'Liechtenstein', 'Vaduz', 'Q347'],
  ['LT', 'Lituanie', 'Vilnius', 'Q37'],
  ['LU', 'Luxembourg', 'Luxembourg', 'Q32'],
  ['MG', 'Madagascar', 'Antananarivo', 'Q1019'],
  ['MW', 'Malawi', 'Lilongwe', 'Q1020'],
  ['MY', 'Malaisie', 'Kuala Lumpur', 'Q833'],
  ['MV', 'Maldives', 'Malé', 'Q826'],
  ['ML', 'Mali', 'Bamako', 'Q912'],
  ['MT', 'Malte', 'La Valette', 'Q233'],
  ['MH', 'Îles Marshall', 'Majuro', 'Q709'],
  ['MR', 'Mauritanie', 'Nouakchott', 'Q1025'],
  ['MU', 'Maurice', 'Port-Louis', 'Q1027'],
  ['MX', 'Mexique', 'Mexico', 'Q96'],
  ['FM', 'Micronésie', 'Palikir', 'Q702'],
  ['MD', 'Moldavie', 'Chișinău', 'Q217'],
  ['MC', 'Monaco', 'Monaco', 'Q235'],
  ['MN', 'Mongolie', 'Oulan-Bator', 'Q711'],
  ['ME', 'Monténégro', 'Podgorica', 'Q236'],
  ['MA', 'Maroc', 'Rabat', 'Q1028'],
  ['MZ', 'Mozambique', 'Maputo', 'Q1029'],
  ['MM', 'Myanmar', 'Naypyidaw', 'Q836'],
  ['NA', 'Namibie', 'Windhoek', 'Q1030'],
  ['NP', 'Népal', 'Katmandou', 'Q837'],
  ['NZ', 'Nouvelle-Zélande', 'Wellington', 'Q664'],
  ['NI', 'Nicaragua', 'Managua', 'Q811'],
  ['NE', 'Niger', 'Niamey', 'Q1032'],
  ['NG', 'Nigeria', 'Abuja', 'Q1033'],
  ['KP', 'Corée du Nord', 'Pyongyang', 'Q423'],
  ['MK', 'Macédoine du Nord', 'Skopje', 'Q221'],
  ['NO', 'Norvège', 'Oslo', 'Q20'],
  ['OM', 'Oman', 'Mascate', 'Q842'],
  ['PK', 'Pakistan', 'Islamabad', 'Q843'],
  ['PW', 'Palaos', 'Ngerulmud', 'Q695'],
  ['PA', 'Panama', 'Panama', 'Q804'],
  ['PG', 'Papouasie-Nouvelle-Guinée', 'Port Moresby', 'Q691'],
  ['PY', 'Paraguay', 'Asunción', 'Q733'],
  ['PE', 'Pérou', 'Lima', 'Q419'],
  ['PH', 'Philippines', 'Manille', 'Q928'],
  ['PL', 'Pologne', 'Varsovie', 'Q36'],
  ['QA', 'Qatar', 'Doha', 'Q846'],
  ['RO', 'Roumanie', 'Bucarest', 'Q218'],
  ['RW', 'Rwanda', 'Kigali', 'Q1037'],
  ['KN', 'Saint-Christophe-et-Niévès', 'Basseterre', 'Q763'],
  ['LC', 'Sainte-Lucie', 'Castries', 'Q760'],
  ['VC', 'Saint-Vincent-et-les-Grenadines', 'Kingstown', 'Q757'],
  ['WS', 'Samoa', 'Apia', 'Q683'],
  ['SM', 'Saint-Marin', 'Saint-Marin', 'Q238'],
  ['SA', 'Arabie saoudite', 'Riyad', 'Q851'],
  ['SN', 'Sénégal', 'Dakar', 'Q1041'],
  ['SC', 'Seychelles', 'Victoria', 'Q1042'],
  ['SL', 'Sierra Leone', 'Freetown', 'Q1044'],
  ['SG', 'Singapour', 'Singapour', 'Q334'],
  ['SK', 'Slovaquie', 'Bratislava', 'Q214'],
  ['SB', 'Îles Salomon', 'Honiara', 'Q685'],
  ['SO', 'Somalie', 'Mogadiscio', 'Q1045'],
  ['KR', 'Corée du Sud', 'Séoul', 'Q884'],
  ['SS', 'Soudan du Sud', 'Djouba', 'Q958'],
  ['ES', 'Espagne', 'Madrid', 'Q29'],
  ['LK', 'Sri Lanka', 'Sri Jayawardenepura Kotte', 'Q854'],
  ['SD', 'Soudan', 'Khartoum', 'Q1049'],
  ['SR', 'Suriname', 'Paramaribo', 'Q730'],
  ['SE', 'Suède', 'Stockholm', 'Q34'],
  ['CH', 'Suisse', 'Berne', 'Q39'],
  ['SY', 'Syrie', 'Damas', 'Q858'],
  ['TJ', 'Tadjikistan', 'Douchanbé', 'Q863'],
  ['TZ', 'Tanzanie', 'Dodoma', 'Q924'],
  ['TH', 'Thaïlande', 'Bangkok', 'Q869'],
  ['TL', 'Timor oriental', 'Dili', 'Q574'],
  ['TG', 'Togo', 'Lomé', 'Q945'],
  ['TO', 'Tonga', 'Nuku’alofa', 'Q678'],
  ['TT', 'Trinité-et-Tobago', 'Port-d’Espagne', 'Q754'],
  ['TN', 'Tunisie', 'Tunis', 'Q948'],
  ['TR', 'Turquie', 'Ankara', 'Q43'],
  ['TM', 'Turkménistan', 'Achgabat', 'Q874'],
  ['TV', 'Tuvalu', 'Funafuti', 'Q672'],
  ['UG', 'Ouganda', 'Kampala', 'Q1036'],
  ['UA', 'Ukraine', 'Kyiv', 'Q212'],
  ['AE', 'Émirats arabes unis', 'Abou Dabi', 'Q878'],
  ['GB', 'Royaume-Uni', 'Londres', 'Q145'],
  ['US', 'États-Unis', 'Washington, D.C.', 'Q30'],
  ['UY', 'Uruguay', 'Montevideo', 'Q77'],
  ['UZ', 'Ouzbékistan', 'Tachkent', 'Q265'],
  ['VU', 'Vanuatu', 'Port-Vila', 'Q686'],
  ['VA', 'Vatican', 'Cité du Vatican', 'Q237'],
  ['VE', 'Venezuela', 'Caracas', 'Q717'],
  ['VN', 'Viêt Nam', 'Hanoï', 'Q881'],
  ['ZM', 'Zambie', 'Lusaka', 'Q953'],
  ['ZW', 'Zimbabwe', 'Harare', 'Q954'],
] as const;

const makeQuestion = (row: CapitalRow, index: number): Question => {
  const [iso, country, capital, wikidataId] = row;
  const url = `https://www.wikidata.org/wiki/${wikidataId}`;
  const factId = `geography-capital-${iso.toLowerCase()}`;
  return {
    id: factId,
    factId,
    version: 1,
    type: 'flashcard',
    question: `Quelle est la capitale de ${country} ?`,
    answer: capital,
    acceptedAnswers: [capital],
    explanation: `${capital} est la capitale de ${country}.`,
    category: 'Géographie',
    subcategory: 'Capitales du monde',
    tags: ['géographie', 'capitale', 'monde'],
    difficulty: index < 40 ? 1 : index < 95 ? 2 : 3,
    source,
    provenance: {
      factId,
      source,
      url,
      license,
      checkedAt,
      method,
      status: 'approved',
    },
  };
};

export const verifiedGeographyBatch: VerifiedContentBatch = {
  id: 'geography-capitals-2026-09',
  questions: rows.map(makeQuestion),
  source,
  sourceUrl: 'https://www.wikidata.org/wiki/Wikidata:Licensing',
  license,
  checkedAt,
  method,
  status: 'approved',
};

export default verifiedGeographyBatch;
