import type { Question, QuestionProvenance } from '../domain/types.ts';
import type { VerifiedContentBatch } from './catalog.ts';

/**
 * Stable facts about marine ecology and coastal systems, reviewed against
 * NOAA educational resources.  Each row expresses one distinct concept;
 * there are no generated wording variants in this batch.
 */
const CHECKED_AT = '2026-09-15';
const SOURCE = 'NOAA National Ocean Service — Ocean and coastal science';
const LICENSE = 'U.S. Government work — public domain (17 U.S.C. §105)';
const METHOD = 'Relecture éditoriale de l’énoncé, de la réponse et de l’explication dans la ressource NOAA indiquée; fait stable et distinct, sans variante générée.';

const URLS = {
  ocean: 'https://oceanservice.noaa.gov/facts/',
  corals: 'https://oceanservice.noaa.gov/education/tutorial_corals/',
  estuaries: 'https://oceanservice.noaa.gov/education/tutorial_estuaries/',
  currents: 'https://oceanservice.noaa.gov/education/tutorial_currents/',
  tides: 'https://oceanservice.noaa.gov/education/tutorial_tides/',
  ecosystems: 'https://oceanservice.noaa.gov/ecosystems/',
} as const;

type Row = readonly [
  id: string,
  subcategory: string,
  question: string,
  answer: string,
  explanation: string,
  difficulty: 1 | 2 | 3,
  sourceUrl: string,
];

const rows: readonly Row[] = [
  ['ocean-salinity-definition', 'Océanographie', 'Que mesure la salinité de l’eau de mer ?', 'La quantité de sels dissous', 'La salinité décrit la concentration globale de sels dissous dans l’eau.', 1, URLS.ocean],
  ['ocean-photic-zone', 'Écosystèmes marins', 'Comment appelle-t-on la zone éclairée de l’océan où la photosynthèse est possible ?', 'La zone photique', 'La lumière y est suffisamment disponible pour alimenter la photosynthèse des organismes producteurs.', 1, URLS.ocean],
  ['ocean-aphotic-zone', 'Écosystèmes marins', 'Comment appelle-t-on la partie de l’océan qui reçoit très peu ou pas de lumière ?', 'La zone aphotique', 'À cette profondeur, la lumière ne permet généralement plus une photosynthèse significative.', 1, URLS.ocean],
  ['ocean-plankton-definition', 'Écosystèmes marins', 'Que désigne le plancton ?', 'Les organismes qui dérivent avec les courants', 'Le plancton regroupe des organismes incapables de lutter efficacement contre les mouvements de l’eau.', 1, URLS.ocean],
  ['ocean-phytoplankton', 'Écosystèmes marins', 'Quel groupe planctonique réalise principalement la photosynthèse ?', 'Le phytoplancton', 'Le phytoplancton comprend des organismes microscopiques photosynthétiques qui produisent de la matière organique.', 1, URLS.ocean],
  ['ocean-zooplankton', 'Écosystèmes marins', 'Quel groupe planctonique se nourrit d’autres organismes ou particules organiques ?', 'Le zooplancton', 'Le zooplancton regroupe des animaux et d’autres organismes hétérotrophes vivant dans le plancton.', 1, URLS.ocean],
  ['ocean-nekton', 'Écosystèmes marins', 'Comment appelle-t-on les organismes marins capables de nager contre les courants ?', 'Le necton', 'Les poissons, les calmars et de nombreux mammifères marins font partie du necton.', 1, URLS.ocean],
  ['ocean-benthos', 'Écosystèmes marins', 'Comment appelle-t-on les organismes vivant sur ou dans les fonds marins ?', 'Le benthos', 'Le benthos comprend les organismes associés au fond, qu’ils y soient fixés, rampants ou enfouis.', 1, URLS.ocean],
  ['ocean-primary-producers', 'Écosystèmes marins', 'Quel rôle jouent les producteurs primaires dans un réseau alimentaire marin ?', 'Ils fabriquent de la matière organique', 'Ils utilisent notamment la lumière pour transformer du carbone inorganique en matière organique.', 1, URLS.ecosystems],
  ['ocean-food-web', 'Écosystèmes marins', 'Qu’est-ce qu’un réseau alimentaire ?', 'Un ensemble de chaînes alimentaires reliées', 'Les relations de prédation d’un écosystème forment généralement un réseau plutôt qu’une seule chaîne.', 1, URLS.ecosystems],
  ['ocean-decomposer-role', 'Écosystèmes marins', 'Quel rôle les décomposeurs jouent-ils dans un écosystème ?', 'Ils recyclent la matière organique', 'Ils transforment les restes et déchets organiques et rendent des éléments nutritifs disponibles.', 1, URLS.ecosystems],
  ['ocean-detritus', 'Écosystèmes marins', 'Que désigne le détritus dans un réseau marin ?', 'De la matière organique morte', 'Les débris d’organismes constituent une source d’énergie pour de nombreux organismes détritivores.', 1, URLS.ecosystems],
  ['ocean-nutrient-cycling', 'Écosystèmes marins', 'Que décrit le cycle des nutriments ?', 'La circulation des éléments entre organismes et environnement', 'Des éléments comme l’azote et le phosphore passent du milieu aux organismes puis y retournent.', 2, URLS.ecosystems],
  ['ocean-trophic-level', 'Écosystèmes marins', 'Qu’est-ce qu’un niveau trophique ?', 'La position d’un organisme dans un réseau alimentaire', 'Un producteur, un consommateur et un décomposeur occupent des positions trophiques différentes.', 1, URLS.ecosystems],
  ['coral-polyp', 'Coraux', 'Quelle unité biologique construit un corail colonial ?', 'Le polype', 'Un polype corallien est un petit animal apparenté aux anémones et aux méduses.', 1, URLS.corals],
  ['coral-cnidarian', 'Coraux', 'À quel embranchement appartiennent les coraux ?', 'Aux cnidaires', 'Les coraux partagent cet embranchement avec les méduses et les anémones.', 1, URLS.corals],
  ['coral-calcium-carbonate', 'Coraux', 'Quelle substance minérale les coraux durs déposent-ils pour construire leur squelette ?', 'Le carbonate de calcium', 'Les polypes sécrètent du carbonate de calcium qui forme la structure rigide du récif.', 1, URLS.corals],
  ['coral-zooxanthellae', 'Coraux', 'Comment appelle-t-on les algues microscopiques vivant en symbiose avec de nombreux coraux ?', 'Les zooxanthelles', 'Ces algues photosynthétiques vivent dans les tissus du corail et lui fournissent une partie de leurs produits.', 2, URLS.corals],
  ['coral-symbiosis', 'Coraux', 'Quel type de relation unit généralement un corail constructeur de récif et ses algues symbiotiques ?', 'Une mutualité', 'Le corail reçoit des produits de la photosynthèse et l’algue bénéficie d’un habitat et de substances utiles.', 2, URLS.corals],
  ['coral-bleaching', 'Coraux', 'Que se passe-t-il lors du blanchissement corallien ?', 'Le corail perd ou expulse ses algues symbiotiques', 'Sans leurs pigments, les tissus laissent apparaître le squelette clair; le blanchissement peut être réversible ou non.', 1, URLS.corals],
  ['coral-reef-habitat', 'Coraux', 'Pourquoi les récifs coralliens sont-ils importants pour de nombreuses espèces ?', 'Ils fournissent habitat et abris', 'Le relief du récif crée des surfaces, refuges et zones d’alimentation pour de nombreux organismes.', 1, URLS.corals],
  ['coral-larval-dispersal', 'Coraux', 'Comment de nouveaux sites coralliens peuvent-ils être colonisés ?', 'Par la dispersion de larves', 'Après la reproduction, des larves peuvent être transportées par les courants avant de se fixer.', 2, URLS.corals],
  ['coral-planula', 'Coraux', 'Comment appelle-t-on la larve nageuse des coraux ?', 'La planula', 'La planula est une larve ciliée qui peut se fixer puis se métamorphoser en polype.', 2, URLS.corals],
  ['coral-budding', 'Coraux', 'Quel mode de reproduction asexuée permet à un polype corallien de produire un autre polype ?', 'Le bourgeonnement', 'Un bourgeon se forme sur le polype parent et devient un nouvel individu.', 1, URLS.corals],
  ['coral-spawning', 'Coraux', 'Comment les coraux peuvent-ils libérer leurs gamètes dans l’eau ?', 'Par une ponte synchronisée', 'De nombreuses espèces libèrent ovules et spermatozoïdes dans la colonne d’eau selon des signaux environnementaux.', 2, URLS.corals],
  ['coral-hard-soft', 'Coraux', 'Quelle caractéristique distingue les coraux durs des coraux mous ?', 'Les coraux durs construisent un squelette calcaire rigide', 'Les coraux mous n’édifient pas le même squelette externe massif que les coraux constructeurs de récifs.', 1, URLS.corals],
  ['coral-shallow-light', 'Coraux', 'Pourquoi beaucoup de coraux constructeurs vivent-ils dans des eaux peu profondes ?', 'Parce que leurs algues ont besoin de lumière', 'La symbiose photosynthétique dépend d’un accès suffisant à la lumière.', 1, URLS.corals],
  ['coral-acidification', 'Coraux', 'Quel effet l’acidification de l’océan peut-elle avoir sur la construction des récifs ?', 'Elle peut rendre la calcification plus difficile', 'La chimie de l’eau modifiée peut réduire la disponibilité des ions nécessaires à la formation du carbonate de calcium.', 2, URLS.corals],
  ['coral-rubble', 'Coraux', 'Que devient souvent le squelette d’un corail mort soumis à l’érosion ?', 'Il contribue aux débris et sédiments du récif', 'La fragmentation du carbonate produit du gravier et du sable qui participent au relief récifal.', 1, URLS.corals],
  ['estuary-brackish', 'Estuaires', 'Comment appelle-t-on généralement l’eau mélangée d’un estuaire ?', 'L’eau saumâtre', 'L’eau saumâtre a une salinité intermédiaire entre l’eau douce et l’eau de mer.', 1, URLS.estuaries],
  ['estuary-tidal', 'Estuaires', 'Quel phénomène influence régulièrement le niveau d’eau d’un estuaire côtier ?', 'La marée', 'Les estuaires sont souvent soumis à l’alternance de la montée et de la descente de la mer.', 1, URLS.estuaries],
  ['estuary-nutrient-rich', 'Estuaires', 'Pourquoi les estuaires sont-ils souvent riches en nutriments ?', 'Les apports fluviaux et le brassage y concentrent des nutriments', 'Les rivières apportent des éléments et les mélanges favorisent leur disponibilité pour les producteurs.', 2, URLS.estuaries],
  ['estuary-nursery', 'Estuaires', 'Quel rôle de nombreux estuaires jouent-ils pour les poissons et crustacés ?', 'Une fonction de nurserie', 'Les eaux peu profondes et les habitats structurés offrent nourriture et refuge aux jeunes animaux.', 1, URLS.estuaries],
  ['estuary-marsh', 'Estuaires', 'Quel habitat végétalisé est fréquent dans les estuaires tempérés ?', 'Le marais salé', 'Les plantes tolérantes au sel y poussent dans la zone régulièrement influencée par la marée.', 1, URLS.estuaries],
  ['estuary-mangrove', 'Estuaires', 'Quel arbre ou arbuste tolérant le sel forme des forêts dans des estuaires tropicaux ?', 'La mangrove', 'Les mangroves occupent des côtes tropicales et leurs racines stabilisent les sédiments.', 1, URLS.estuaries],
  ['estuary-oyster-reef', 'Estuaires', 'Quel animal peut former des récifs dans certains estuaires ?', 'L’huître', 'Les huîtres fixées s’agrègent et créent un habitat tridimensionnel pour d’autres organismes.', 1, URLS.estuaries],
  ['estuary-filter-feeder', 'Estuaires', 'Comment une huître se nourrit-elle principalement ?', 'En filtrant des particules de l’eau', 'Elle pompe l’eau et retient notamment du plancton et des particules organiques.', 1, URLS.estuaries],
  ['estuary-sediment-trap', 'Estuaires', 'Quel effet les estuaires peuvent-ils avoir sur les sédiments apportés par les fleuves ?', 'Ils peuvent en retenir une partie', 'Le ralentissement et le mélange des eaux favorisent le dépôt de sédiments dans l’estuaire.', 1, URLS.estuaries],
  ['estuary-wetland-flood', 'Estuaires', 'Comment les zones humides estuariennes peuvent-elles limiter les effets des crues ?', 'Elles stockent et ralentissent une partie de l’eau', 'Les végétaux et les sols humides absorbent, retiennent et dissipent une partie du flux.', 1, URLS.estuaries],
  ['estuary-storm-buffer', 'Estuaires', 'Quel service côtier les marais et mangroves peuvent-ils rendre pendant une tempête ?', 'Atténuer une partie de l’énergie des vagues', 'La végétation et les racines augmentent la rugosité et dissipent une partie du mouvement de l’eau.', 2, URLS.estuaries],
  ['estuary-anadromous-fish', 'Estuaires', 'Pourquoi les estuaires sont-ils importants pour certains poissons migrateurs ?', 'Ils relient les eaux douces et marines', 'Ils constituent une zone de transition pour les espèces qui passent d’un milieu à l’autre.', 1, URLS.estuaries],
  ['estuary-residence-time', 'Estuaires', 'Que décrit le temps de résidence d’un estuaire ?', 'Le temps moyen de séjour de l’eau', 'Il indique combien de temps l’eau reste dans le système avant d’en sortir.', 3, URLS.estuaries],
  ['estuary-eutrophication', 'Estuaires', 'Que peut provoquer un apport excessif de nutriments dans un estuaire ?', 'Une prolifération excessive d’algues', 'L’excès d’azote ou de phosphore peut stimuler les algues et perturber l’équilibre de l’écosystème.', 2, URLS.estuaries],
  ['estuary-hypoxia', 'Estuaires', 'Comment appelle-t-on une eau dont la concentration en oxygène est très faible ?', 'Une eau hypoxique', 'La décomposition d’une grande quantité de matière organique peut consommer l’oxygène dissous.', 2, URLS.estuaries],
  ['estuary-salinity-gradient', 'Estuaires', 'Comment la salinité varie-t-elle souvent de l’amont vers l’embouchure d’un estuaire ?', 'Elle augmente généralement', 'L’influence de l’eau de mer devient plus forte à mesure que l’on se rapproche de l’embouchure.', 1, URLS.estuaries],
  ['estuary-restoration', 'Estuaires', 'Que cherche à rétablir la restauration d’un estuaire ?', 'Les fonctions et habitats naturels du système', 'La restauration vise notamment les habitats, les flux d’eau et la qualité écologique.', 1, URLS.estuaries],
  ['tide-gravity-moon', 'Marées', 'Quel astre exerce la principale influence gravitationnelle sur les marées terrestres ?', 'La Lune', 'La gravité lunaire contribue fortement aux variations périodiques du niveau de la mer.', 1, URLS.tides],
  ['tide-sun-influence', 'Marées', 'Le Soleil influence-t-il aussi les marées ?', 'Oui', 'La gravité solaire s’ajoute à l’influence lunaire, malgré la plus grande distance du Soleil.', 1, URLS.tides],
  ['tide-range', 'Marées', 'Que désigne l’amplitude de marée ?', 'La différence entre pleine mer et basse mer', 'Elle mesure l’écart vertical entre les deux niveaux extrêmes d’un cycle.', 1, URLS.tides],
  ['tide-diurnal', 'Marées', 'Que signifie une marée diurne ?', 'Une pleine mer et une basse mer par jour lunaire', 'Dans un régime diurne, un seul cycle de marée se produit approximativement par jour lunaire.', 3, URLS.tides],
  ['tide-semidiurnal', 'Marées', 'Que signifie une marée semi-diurne ?', 'Deux pleines mers et deux basses mers par jour lunaire', 'Les deux cycles quotidiens ont des hauteurs proches dans le régime semi-diurne régulier.', 2, URLS.tides],
  ['tide-mixed', 'Marées', 'Que caractérise un régime de marée mixte ?', 'Des hauteurs inégales entre les marées quotidiennes', 'Un régime mixte combine deux cycles par jour avec des hauteurs sensiblement différentes.', 3, URLS.tides],
  ['tide-bay-resonance', 'Marées', 'Pourquoi la forme d’une baie peut-elle amplifier une marée ?', 'Parce qu’elle peut entrer en résonance avec la période de la marée', 'La géométrie et la profondeur d’une baie peuvent renforcer l’oscillation de l’eau.', 3, URLS.tides],
  ['tide-friction', 'Marées', 'Quel processus dissipe une partie de l’énergie des marées ?', 'Le frottement avec les fonds et les côtes', 'Le mouvement de l’eau rencontre des obstacles et convertit une partie de son énergie en chaleur.', 2, URLS.tides],
  ['tide-tidal-current', 'Marées', 'Comment appelle-t-on le déplacement horizontal de l’eau lié aux marées ?', 'Le courant de marée', 'Les courants de flot et de jusant accompagnent la montée et la descente de la mer.', 1, URLS.tides],
  ['tide-flood-current', 'Marées', 'Comment appelle-t-on le courant associé à la montée de la marée ?', 'Le flot', 'Le flot porte l’eau vers les côtes ou les zones intérieures d’un estuaire.', 1, URLS.tides],
  ['tide-ebb-current', 'Marées', 'Comment appelle-t-on le courant associé à la descente de la marée ?', 'Le jusant', 'Le jusant porte l’eau vers le large ou vers l’embouchure.', 1, URLS.tides],
  ['tide-tidal-flat', 'Marées', 'Qu’est-ce qu’un estran vaseux ou sableux ?', 'Une zone découverte et recouverte par la marée', 'Cet habitat intertidal alterne immersion et exposition au cours du cycle de marée.', 1, URLS.tides],
  ['tide-intertidal-zone', 'Marées', 'Comment appelle-t-on la zone comprise entre pleine mer et basse mer ?', 'La zone intertidale', 'Elle est régulièrement soumise à l’immersion puis à l’émersion.', 1, URLS.tides],
  ['tide-supratidal', 'Marées', 'Quelle zone côtière n’est atteinte par la mer que lors des très hautes mers ou tempêtes ?', 'La zone supratidale', 'Elle se situe au-dessus de la zone intertidale et reçoit surtout les embruns ou les événements extrêmes.', 3, URLS.tides],
  ['current-wind-driven', 'Courants marins', 'Quelle force met souvent en mouvement les courants de surface de l’océan ?', 'Le vent', 'Le vent transfère de l’énergie à la surface et entraîne des mouvements d’eau.', 1, URLS.currents],
  ['current-thermohaline', 'Courants marins', 'Que signifie le terme thermohalin ?', 'Qui dépend de la température et de la salinité', 'La circulation thermohaline est liée aux variations de densité dues à ces deux propriétés.', 2, URLS.currents],
  ['current-ekman', 'Courants marins', 'Que décrit le transport d’Ekman ?', 'Le transport moyen de l’eau dû au vent et à la rotation terrestre', 'Le mouvement intégré sur la couche superficielle n’est pas exactement dans la direction du vent.', 3, URLS.currents],
  ['current-upwelling', 'Courants marins', 'Qu’est-ce qu’une remontée d’eau ou upwelling ?', 'La remontée d’eau profonde vers la surface', 'Elle apporte souvent des eaux plus froides et riches en nutriments vers la zone éclairée.', 1, URLS.currents],
  ['current-downwelling', 'Courants marins', 'Qu’est-ce qu’une plongée d’eau ou downwelling ?', 'La descente d’eau de surface vers la profondeur', 'Elle transfère de l’eau et des gaz dissous depuis la surface vers l’océan profond.', 2, URLS.currents],
  ['current-upwelling-food', 'Courants marins', 'Pourquoi les remontées d’eau peuvent-elles favoriser la productivité biologique ?', 'Elles remontent des nutriments', 'Les nutriments profonds peuvent soutenir la croissance du phytoplancton dans la zone éclairée.', 1, URLS.currents],
  ['current-western-boundary', 'Courants marins', 'Quelle caractéristique ont souvent les courants de bord ouest des gyres ?', 'Ils sont étroits et rapides', 'La dynamique des gyres concentre un transport important le long de leur bord occidental.', 3, URLS.currents],
  ['current-continental-shelf', 'Courants marins', 'Qu’est-ce qu’un courant de plateau continental ?', 'Un courant circulant au-dessus d’un plateau peu profond', 'Le plateau continental est la partie immergée et peu profonde de la marge d’un continent.', 2, URLS.currents],
  ['current-longshore', 'Courants marins', 'Comment appelle-t-on le courant qui longe une plage parallèlement au rivage ?', 'Le courant littoral', 'Les vagues obliques peuvent déplacer l’eau et les sédiments le long de la côte.', 1, URLS.currents],
  ['current-rip', 'Courants marins', 'Qu’est-ce qu’un courant d’arrachement ?', 'Un courant étroit qui repart vers le large depuis la plage', 'Il se forme lorsque l’eau accumulée près du rivage retourne rapidement vers le large.', 2, URLS.currents],
  ['current-ocean-conveyor', 'Courants marins', 'Que transporte la circulation océanique mondiale ?', 'De la chaleur, des sels, des nutriments et des gaz', 'Les courants redistribuent de l’énergie et de la matière entre régions et profondeurs.', 1, URLS.currents],
  ['current-carbon-pump', 'Écosystèmes marins', 'Quel mécanisme biologique exporte du carbone de la surface vers l’océan profond ?', 'La pompe biologique', 'La production puis la sédimentation de matière organique transfèrent du carbone vers les profondeurs.', 2, URLS.ecosystems],
  ['current-marine-snow', 'Écosystèmes marins', 'Que désigne la neige marine ?', 'Des particules organiques qui coulent dans l’océan', 'Des agrégats de restes et de déchets biologiques descendent depuis les eaux de surface.', 1, URLS.ecosystems],
  ['ocean-oxygen-production', 'Écosystèmes marins', 'Quels organismes marins produisent une grande partie de l’oxygène par photosynthèse ?', 'Le phytoplancton et les algues', 'Ces producteurs utilisent la lumière et le dioxyde de carbone pour fabriquer de la matière organique et libérer de l’oxygène.', 1, URLS.ecosystems],
  ['ocean-respiration', 'Écosystèmes marins', 'Que font les organismes lors de la respiration cellulaire ?', 'Ils libèrent de l’énergie à partir de matière organique', 'La respiration utilise généralement de l’oxygène et transforme la matière organique en énergie utilisable.', 1, URLS.ecosystems],
  ['ocean-photosynthesis', 'Écosystèmes marins', 'Quelle énergie alimente la photosynthèse des algues marines ?', 'L’énergie lumineuse', 'Les pigments photosynthétiques captent la lumière pour convertir du carbone inorganique en matière organique.', 1, URLS.ecosystems],
  ['ocean-kelp-forest', 'Habitats marins', 'Qu’est-ce qu’une forêt de kelp ?', 'Un habitat dominé par de grandes algues brunes', 'Les kelps forment une structure en hauteur qui fournit nourriture et refuge à de nombreuses espèces.', 1, URLS.ecosystems],
  ['ocean-seagrass', 'Habitats marins', 'Quel type de plante forme les herbiers marins ?', 'Des plantes à fleurs adaptées à la vie immergée', 'Les herbiers sont constitués d’angiospermes marines, et non d’algues.', 2, URLS.ecosystems],
  ['ocean-seagrass-root', 'Habitats marins', 'Quel rôle les racines des herbiers marins jouent-elles dans les sédiments ?', 'Elles les stabilisent', 'Les racines et rhizomes réduisent la remise en suspension des sédiments.', 1, URLS.ecosystems],
  ['ocean-seagrass-nursery', 'Habitats marins', 'Pourquoi les herbiers marins servent-ils de nurserie ?', 'Ils offrent refuge et nourriture aux jeunes animaux', 'Le feuillage dense protège de nombreux juvéniles des prédateurs et fournit des proies.', 1, URLS.ecosystems],
  ['ocean-saltmarsh-halophyte', 'Habitats côtiers', 'Comment appelle-t-on une plante capable de tolérer de fortes concentrations de sel ?', 'Une halophyte', 'Les halophytes possèdent des adaptations leur permettant de vivre dans des sols ou eaux salés.', 2, URLS.estuaries],
  ['ocean-mangrove-roots', 'Habitats côtiers', 'Quel rôle les racines de mangrove jouent-elles dans la vase ?', 'Elles piègent et stabilisent les sédiments', 'Le réseau de racines ralentit l’eau et favorise l’accumulation de particules.', 1, URLS.estuaries],
  ['ocean-mangrove-propagule', 'Habitats côtiers', 'Comment certaines mangroves dispersent-elles leurs jeunes plants ?', 'Par des propagules flottantes', 'Les propagules peuvent flotter puis s’enraciner dans un habitat favorable.', 2, URLS.estuaries],
  ['ocean-marine-protected-area', 'Conservation', 'Qu’est-ce qu’une aire marine protégée ?', 'Un espace marin soumis à des règles de protection', 'La réglementation vise à conserver des habitats, des espèces ou des processus écologiques.', 1, URLS.ecosystems],
  ['ocean-habitat-connectivity', 'Conservation', 'Que signifie la connectivité des habitats côtiers ?', 'Le maintien des liens entre habitats utilisés par les espèces', 'Les espèces peuvent dépendre de plusieurs habitats reliés au cours de leur cycle de vie.', 2, URLS.ecosystems],
  ['ocean-biodiversity', 'Conservation', 'Que désigne la biodiversité ?', 'La diversité des êtres vivants et de leurs interactions', 'Elle comprend la diversité génétique, la diversité des espèces et celle des écosystèmes.', 1, URLS.ecosystems],
  ['ocean-keystone-species', 'Écologie', 'Qu’est-ce qu’une espèce clé de voûte ?', 'Une espèce dont l’effet écologique est disproportionné', 'Sa disparition peut modifier fortement la structure ou le fonctionnement de la communauté.', 2, URLS.ecosystems],
  ['ocean-invasive-species', 'Écologie', 'Comment appelle-t-on une espèce introduite qui cause des dommages dans un nouvel écosystème ?', 'Une espèce exotique envahissante', 'Elle se propage et peut perturber les espèces, habitats ou fonctions écologiques locaux.', 1, URLS.ecosystems],
  ['ocean-native-species', 'Écologie', 'Qu’est-ce qu’une espèce indigène ?', 'Une espèce présente naturellement dans une région', 'Sa présence ne résulte pas d’une introduction humaine récente dans cette région.', 1, URLS.ecosystems],
  ['ocean-habitat-definition', 'Écologie', 'Qu’est-ce qu’un habitat ?', 'Le lieu et les conditions où vit un organisme', 'Un habitat fournit notamment des ressources, un abri et des conditions physiques compatibles avec la vie.', 1, URLS.ecosystems],
  ['ocean-ecosystem-definition', 'Écologie', 'Qu’est-ce qu’un écosystème ?', 'Une communauté d’organismes et son environnement', 'Un écosystème comprend les êtres vivants, les facteurs physiques et leurs interactions.', 1, URLS.ecosystems],
  ['ocean-ecological-niche', 'Écologie', 'Que décrit la niche écologique d’une espèce ?', 'Son rôle et ses conditions d’existence dans l’écosystème', 'La niche inclut les ressources utilisées, les interactions et les conditions tolérées.', 2, URLS.ecosystems],
  ['ocean-population-community', 'Écologie', 'Quelle différence distingue une population d’une communauté ?', 'Une population regroupe une espèce; une communauté en regroupe plusieurs', 'Une communauté rassemble les populations d’espèces différentes qui coexistent dans un lieu.', 1, URLS.ecosystems],
  ['ocean-competition', 'Écologie', 'Que se disputent des organismes en compétition ?', 'Des ressources limitées', 'La nourriture, l’espace ou la lumière peuvent limiter la croissance et la reproduction.', 1, URLS.ecosystems],
  ['ocean-predation', 'Écologie', 'Qu’est-ce que la prédation ?', 'Une interaction où un organisme capture et consomme une proie', 'Le prédateur obtient de l’énergie tandis que la proie est tuée dans cette interaction.', 1, URLS.ecosystems],
  ['ocean-herbivory', 'Écologie', 'Comment appelle-t-on la consommation de végétaux ou d’algues par un animal ?', 'L’herbivorie', 'L’herbivore se nourrit de producteurs primaires vivants.', 1, URLS.ecosystems],
  ['ocean-mutualism', 'Écologie', 'Qu’est-ce qu’une relation mutualiste ?', 'Une relation bénéfique aux deux partenaires', 'Chaque partenaire obtient un bénéfice net de l’interaction.', 1, URLS.ecosystems],
  ['ocean-commensalism', 'Écologie', 'Qu’est-ce que le commensalisme ?', 'Une relation où un partenaire bénéficie sans effet notable sur l’autre', 'Le bénéfice concerne un organisme tandis que l’autre n’est généralement ni aidé ni pénalisé.', 2, URLS.ecosystems],
  ['ocean-parasitism', 'Écologie', 'Qu’est-ce que le parasitisme ?', 'Une relation où un organisme bénéficie aux dépens d’un hôte', 'Le parasite obtient des ressources et l’hôte subit un coût.', 1, URLS.ecosystems],
  ['ocean-resilience', 'Écologie', 'Que signifie la résilience d’un écosystème ?', 'Sa capacité à absorber une perturbation et à se rétablir', 'Un écosystème résilient peut retrouver certaines fonctions après une perturbation.', 2, URLS.ecosystems],
  ['ocean-ecological-succession', 'Écologie', 'Que décrit une succession écologique ?', 'Le changement progressif d’une communauté dans le temps', 'Les espèces et les conditions d’un site évoluent selon une séquence de colonisation et de remplacement.', 2, URLS.ecosystems],
  ['ocean-primary-succession', 'Écologie', 'Comment commence une succession primaire ?', 'Sur un substrat dépourvu de sol', 'Elle se déroule sur une surface nouvellement exposée où le sol doit se former progressivement.', 2, URLS.ecosystems],
  ['ocean-secondary-succession', 'Écologie', 'Comment commence une succession secondaire ?', 'Dans un milieu où le sol subsiste après une perturbation', 'La présence de sol et parfois de propagules permet une recolonisation plus rapide.', 2, URLS.ecosystems],
  ['ocean-limiting-factor', 'Écologie', 'Qu’est-ce qu’un facteur limitant ?', 'Une ressource ou condition qui limite une population', 'La croissance ne peut augmenter au-delà de ce que permet le facteur le plus contraignant.', 1, URLS.ecosystems],
  ['ocean-tolerance-range', 'Écologie', 'Que décrit la gamme de tolérance d’une espèce ?', 'Les valeurs environnementales qu’elle peut supporter', 'Elle définit les limites physiques ou chimiques dans lesquelles l’espèce peut vivre.', 2, URLS.ecosystems],
  ['ocean-bioindicator', 'Écologie', 'Qu’est-ce qu’un bioindicateur ?', 'Un organisme ou une mesure révélant l’état d’un milieu', 'La présence, l’abondance ou la santé de certains organismes peut signaler une condition écologique.', 2, URLS.ecosystems],
  ['ocean-microplastics', 'Pollution marine', 'Que désignent les microplastiques ?', 'De très petits fragments ou particules de plastique', 'Ils peuvent provenir de la fragmentation d’objets ou être fabriqués à petite taille.', 1, URLS.ocean],
  ['ocean-biomagnification', 'Pollution marine', 'Que décrit la bioamplification ?', 'L’augmentation d’un contaminant le long du réseau alimentaire', 'Certains contaminants persistants atteignent des concentrations plus élevées chez les prédateurs supérieurs.', 2, URLS.ecosystems],
  ['ocean-bioaccumulation', 'Pollution marine', 'Que signifie la bioaccumulation ?', 'L’accumulation progressive d’une substance dans un organisme', 'Une substance peut entrer plus vite qu’elle n’est éliminée.', 2, URLS.ecosystems],
  ['ocean-noise-pollution', 'Pollution marine', 'Qu’est-ce que la pollution sonore sous-marine ?', 'L’introduction de sons qui perturbent le milieu marin', 'Les bruits anthropiques peuvent modifier la communication et le comportement de certains animaux.', 1, URLS.ocean],
  ['ocean-light-pollution', 'Pollution marine', 'Quel effet la lumière artificielle nocturne peut-elle avoir sur la côte ?', 'Elle peut perturber des comportements naturels', 'La lumière nocturne modifie notamment l’orientation et les rythmes de certaines espèces.', 1, URLS.ocean],
  ['ocean-thermal-pollution', 'Pollution marine', 'Que désigne la pollution thermique ?', 'Une modification artificielle de la température d’un milieu', 'Un rejet de chaleur peut changer les conditions physiques et biologiques locales.', 1, URLS.ocean],
  ['ocean-dead-zone', 'Pollution marine', 'Que désigne une zone morte marine ?', 'Une zone où l’oxygène dissous est trop faible pour beaucoup d’animaux', 'L’hypoxie peut forcer les organismes mobiles à partir et tuer les organismes immobiles.', 1, URLS.ecosystems],
  ['ocean-restoration-reef', 'Conservation', 'Que cherche à faire une restauration de récif ?', 'Rétablir une structure et des fonctions récifales', 'Les projets peuvent restaurer le substrat, les organismes constructeurs et l’habitat associé.', 1, URLS.corals],
  ['ocean-monitoring', 'Conservation', 'Pourquoi surveille-t-on les écosystèmes marins ?', 'Pour détecter les changements et guider la gestion', 'Les séries d’observations permettent de suivre les tendances et d’évaluer les actions.', 1, URLS.ecosystems],
  ['ocean-baseline', 'Conservation', 'Qu’est-ce qu’un état de référence écologique ?', 'Une condition de comparaison pour mesurer un changement', 'Un état de référence aide à déterminer l’ampleur d’une dégradation ou d’une restauration.', 2, URLS.ecosystems],
  ['ocean-adaptive-management', 'Conservation', 'Que signifie une gestion adaptative d’un écosystème ?', 'Ajuster les décisions selon les résultats observés', 'La gestion utilise le suivi et l’apprentissage pour améliorer progressivement les mesures.', 2, URLS.ecosystems],
] as const;

const provenance = (factId: string, sourceUrl: string): QuestionProvenance => ({
  factId,
  source: SOURCE,
  url: sourceUrl,
  license: LICENSE,
  checkedAt: CHECKED_AT,
  method: METHOD,
  status: 'approved',
});

export const VERIFIED_NATURE_NOAA_QUESTIONS: readonly Question[] = rows.map(([id, subcategory, question, answer, explanation, difficulty, sourceUrl]) => {
  const factId = `fact-nature-noaa-${id}`;
  return {
    id: `verified-nature-noaa-${id}`,
    factId,
    version: 1,
    type: 'flashcard',
    category: 'Nature',
    subcategory,
    question,
    answer,
    acceptedAnswers: [answer],
    explanation,
    tags: ['nature', 'écologie', 'océan'],
    difficulty,
    source: SOURCE,
    provenance: provenance(factId, sourceUrl),
  } satisfies Question;
});

export const VERIFIED_NATURE_NOAA_BATCH: VerifiedContentBatch = {
  id: 'nature-noaa-marine-ecology-2026-09',
  questions: VERIFIED_NATURE_NOAA_QUESTIONS,
  source: SOURCE,
  sourceUrl: 'https://oceanservice.noaa.gov/',
  license: LICENSE,
  checkedAt: CHECKED_AT,
  method: `Relecture de ${rows.length} faits indépendants dans les ressources NOAA; chaque question conserve son URL de référence.`,
  status: 'approved',
};

export default VERIFIED_NATURE_NOAA_BATCH;
