import type { Question, QuestionProvenance } from '../domain/types';
import type { VerifiedContentBatch } from './catalog.ts';

/**
 * 118 independent facts from the NIST elemental-data index.
 *
 * Each row identifies one element by its atomic number and chemical symbol.
 * The rows are deliberately kept as source data (rather than question copies):
 * one atomic number = one fact, with a stable factId and a dedicated NIST URL.
 */
const CHECKED_AT = '2026-09-15';
const NIST_SOURCE = 'NIST Basic Atomic Spectroscopic Data — Elemental Data Index';
const NIST_LICENSE = 'NIST — données gouvernementales américaines; conditions d’utilisation NIST';

type ElementRecord = { atomicNumber: number; frenchName: string; symbol: string };

const ELEMENTS: ElementRecord[] = [
  { atomicNumber: 1, frenchName: 'hydrogène', symbol: 'H' },
  { atomicNumber: 2, frenchName: 'hélium', symbol: 'He' },
  { atomicNumber: 3, frenchName: 'lithium', symbol: 'Li' },
  { atomicNumber: 4, frenchName: 'béryllium', symbol: 'Be' },
  { atomicNumber: 5, frenchName: 'bore', symbol: 'B' },
  { atomicNumber: 6, frenchName: 'carbone', symbol: 'C' },
  { atomicNumber: 7, frenchName: 'azote', symbol: 'N' },
  { atomicNumber: 8, frenchName: 'oxygène', symbol: 'O' },
  { atomicNumber: 9, frenchName: 'fluor', symbol: 'F' },
  { atomicNumber: 10, frenchName: 'néon', symbol: 'Ne' },
  { atomicNumber: 11, frenchName: 'sodium', symbol: 'Na' },
  { atomicNumber: 12, frenchName: 'magnésium', symbol: 'Mg' },
  { atomicNumber: 13, frenchName: 'aluminium', symbol: 'Al' },
  { atomicNumber: 14, frenchName: 'silicium', symbol: 'Si' },
  { atomicNumber: 15, frenchName: 'phosphore', symbol: 'P' },
  { atomicNumber: 16, frenchName: 'soufre', symbol: 'S' },
  { atomicNumber: 17, frenchName: 'chlore', symbol: 'Cl' },
  { atomicNumber: 18, frenchName: 'argon', symbol: 'Ar' },
  { atomicNumber: 19, frenchName: 'potassium', symbol: 'K' },
  { atomicNumber: 20, frenchName: 'calcium', symbol: 'Ca' },
  { atomicNumber: 21, frenchName: 'scandium', symbol: 'Sc' },
  { atomicNumber: 22, frenchName: 'titane', symbol: 'Ti' },
  { atomicNumber: 23, frenchName: 'vanadium', symbol: 'V' },
  { atomicNumber: 24, frenchName: 'chrome', symbol: 'Cr' },
  { atomicNumber: 25, frenchName: 'manganèse', symbol: 'Mn' },
  { atomicNumber: 26, frenchName: 'fer', symbol: 'Fe' },
  { atomicNumber: 27, frenchName: 'cobalt', symbol: 'Co' },
  { atomicNumber: 28, frenchName: 'nickel', symbol: 'Ni' },
  { atomicNumber: 29, frenchName: 'cuivre', symbol: 'Cu' },
  { atomicNumber: 30, frenchName: 'zinc', symbol: 'Zn' },
  { atomicNumber: 31, frenchName: 'gallium', symbol: 'Ga' },
  { atomicNumber: 32, frenchName: 'germanium', symbol: 'Ge' },
  { atomicNumber: 33, frenchName: 'arsenic', symbol: 'As' },
  { atomicNumber: 34, frenchName: 'sélénium', symbol: 'Se' },
  { atomicNumber: 35, frenchName: 'brome', symbol: 'Br' },
  { atomicNumber: 36, frenchName: 'krypton', symbol: 'Kr' },
  { atomicNumber: 37, frenchName: 'rubidium', symbol: 'Rb' },
  { atomicNumber: 38, frenchName: 'strontium', symbol: 'Sr' },
  { atomicNumber: 39, frenchName: 'yttrium', symbol: 'Y' },
  { atomicNumber: 40, frenchName: 'zirconium', symbol: 'Zr' },
  { atomicNumber: 41, frenchName: 'niobium', symbol: 'Nb' },
  { atomicNumber: 42, frenchName: 'molybdène', symbol: 'Mo' },
  { atomicNumber: 43, frenchName: 'technétium', symbol: 'Tc' },
  { atomicNumber: 44, frenchName: 'ruthénium', symbol: 'Ru' },
  { atomicNumber: 45, frenchName: 'rhodium', symbol: 'Rh' },
  { atomicNumber: 46, frenchName: 'palladium', symbol: 'Pd' },
  { atomicNumber: 47, frenchName: 'argent', symbol: 'Ag' },
  { atomicNumber: 48, frenchName: 'cadmium', symbol: 'Cd' },
  { atomicNumber: 49, frenchName: 'indium', symbol: 'In' },
  { atomicNumber: 50, frenchName: 'étain', symbol: 'Sn' },
  { atomicNumber: 51, frenchName: 'antimoine', symbol: 'Sb' },
  { atomicNumber: 52, frenchName: 'tellure', symbol: 'Te' },
  { atomicNumber: 53, frenchName: 'iode', symbol: 'I' },
  { atomicNumber: 54, frenchName: 'xénon', symbol: 'Xe' },
  { atomicNumber: 55, frenchName: 'césium', symbol: 'Cs' },
  { atomicNumber: 56, frenchName: 'baryum', symbol: 'Ba' },
  { atomicNumber: 57, frenchName: 'lanthane', symbol: 'La' },
  { atomicNumber: 58, frenchName: 'cérium', symbol: 'Ce' },
  { atomicNumber: 59, frenchName: 'praséodyme', symbol: 'Pr' },
  { atomicNumber: 60, frenchName: 'néodyme', symbol: 'Nd' },
  { atomicNumber: 61, frenchName: 'prométhium', symbol: 'Pm' },
  { atomicNumber: 62, frenchName: 'samarium', symbol: 'Sm' },
  { atomicNumber: 63, frenchName: 'europium', symbol: 'Eu' },
  { atomicNumber: 64, frenchName: 'gadolinium', symbol: 'Gd' },
  { atomicNumber: 65, frenchName: 'terbium', symbol: 'Tb' },
  { atomicNumber: 66, frenchName: 'dysprosium', symbol: 'Dy' },
  { atomicNumber: 67, frenchName: 'holmium', symbol: 'Ho' },
  { atomicNumber: 68, frenchName: 'erbium', symbol: 'Er' },
  { atomicNumber: 69, frenchName: 'thulium', symbol: 'Tm' },
  { atomicNumber: 70, frenchName: 'ytterbium', symbol: 'Yb' },
  { atomicNumber: 71, frenchName: 'lutécium', symbol: 'Lu' },
  { atomicNumber: 72, frenchName: 'hafnium', symbol: 'Hf' },
  { atomicNumber: 73, frenchName: 'tantale', symbol: 'Ta' },
  { atomicNumber: 74, frenchName: 'tungstène', symbol: 'W' },
  { atomicNumber: 75, frenchName: 'rhénium', symbol: 'Re' },
  { atomicNumber: 76, frenchName: 'osmium', symbol: 'Os' },
  { atomicNumber: 77, frenchName: 'iridium', symbol: 'Ir' },
  { atomicNumber: 78, frenchName: 'platine', symbol: 'Pt' },
  { atomicNumber: 79, frenchName: 'or', symbol: 'Au' },
  { atomicNumber: 80, frenchName: 'mercure', symbol: 'Hg' },
  { atomicNumber: 81, frenchName: 'thallium', symbol: 'Tl' },
  { atomicNumber: 82, frenchName: 'plomb', symbol: 'Pb' },
  { atomicNumber: 83, frenchName: 'bismuth', symbol: 'Bi' },
  { atomicNumber: 84, frenchName: 'polonium', symbol: 'Po' },
  { atomicNumber: 85, frenchName: 'astate', symbol: 'At' },
  { atomicNumber: 86, frenchName: 'radon', symbol: 'Rn' },
  { atomicNumber: 87, frenchName: 'francium', symbol: 'Fr' },
  { atomicNumber: 88, frenchName: 'radium', symbol: 'Ra' },
  { atomicNumber: 89, frenchName: 'actinium', symbol: 'Ac' },
  { atomicNumber: 90, frenchName: 'thorium', symbol: 'Th' },
  { atomicNumber: 91, frenchName: 'protactinium', symbol: 'Pa' },
  { atomicNumber: 92, frenchName: 'uranium', symbol: 'U' },
  { atomicNumber: 93, frenchName: 'neptunium', symbol: 'Np' },
  { atomicNumber: 94, frenchName: 'plutonium', symbol: 'Pu' },
  { atomicNumber: 95, frenchName: 'américium', symbol: 'Am' },
  { atomicNumber: 96, frenchName: 'curium', symbol: 'Cm' },
  { atomicNumber: 97, frenchName: 'berkélium', symbol: 'Bk' },
  { atomicNumber: 98, frenchName: 'californium', symbol: 'Cf' },
  { atomicNumber: 99, frenchName: 'einsteinium', symbol: 'Es' },
  { atomicNumber: 100, frenchName: 'fermium', symbol: 'Fm' },
  { atomicNumber: 101, frenchName: 'mendélévium', symbol: 'Md' },
  { atomicNumber: 102, frenchName: 'nobélium', symbol: 'No' },
  { atomicNumber: 103, frenchName: 'lawrencium', symbol: 'Lr' },
  { atomicNumber: 104, frenchName: 'rutherfordium', symbol: 'Rf' },
  { atomicNumber: 105, frenchName: 'dubnium', symbol: 'Db' },
  { atomicNumber: 106, frenchName: 'seaborgium', symbol: 'Sg' },
  { atomicNumber: 107, frenchName: 'bohrium', symbol: 'Bh' },
  { atomicNumber: 108, frenchName: 'hassium', symbol: 'Hs' },
  { atomicNumber: 109, frenchName: 'meitnérium', symbol: 'Mt' },
  { atomicNumber: 110, frenchName: 'darmstadtium', symbol: 'Ds' },
  { atomicNumber: 111, frenchName: 'roentgenium', symbol: 'Rg' },
  { atomicNumber: 112, frenchName: 'copernicium', symbol: 'Cn' },
  { atomicNumber: 113, frenchName: 'nihonium', symbol: 'Nh' },
  { atomicNumber: 114, frenchName: 'flérovium', symbol: 'Fl' },
  { atomicNumber: 115, frenchName: 'moscovium', symbol: 'Mc' },
  { atomicNumber: 116, frenchName: 'livermorium', symbol: 'Lv' },
  { atomicNumber: 117, frenchName: 'tennessine', symbol: 'Ts' },
  { atomicNumber: 118, frenchName: 'oganesson', symbol: 'Og' },
];

const provenanceFor = (atomicNumber: number, factId: string): QuestionProvenance => ({
  factId,
  source: NIST_SOURCE,
  url: `https://physics.nist.gov/cgi-bin/Elements/elInfo.pl?element=${atomicNumber}`,
  license: NIST_LICENSE,
  checkedAt: CHECKED_AT,
  method: 'manual-check-of-NIST-element-index-and-symbol',
  status: 'approved',
});

export const VERIFIED_PERIODIC_TABLE_QUESTIONS: Question[] = ELEMENTS.map(({ atomicNumber, frenchName, symbol }) => {
  const ordinal = String(atomicNumber).padStart(3, '0');
  const id = `science-periodic-atomic-number-${ordinal}-symbol`;
  const factId = `fact-periodic-element-${ordinal}-symbol`;
  return {
    id,
    factId,
    version: 1,
    type: 'flashcard',
    category: 'Sciences',
    subcategory: 'Chimie',
    question: `Quel est le symbole chimique de l’élément de numéro atomique ${atomicNumber} ?`,
    answer: symbol,
    acceptedAnswers: [symbol],
    explanation: `Le numéro atomique ${atomicNumber} correspond à ${frenchName}, dont le symbole est ${symbol}.`,
    difficulty: atomicNumber <= 20 ? 1 : 2,
    tags: ['chimie', 'tableau périodique', 'éléments'],
    provenance: provenanceFor(atomicNumber, factId),
  };
});

export const VERIFIED_PERIODIC_TABLE_BATCH: VerifiedContentBatch = {
  id: 'nist-periodic-table',
  questions: VERIFIED_PERIODIC_TABLE_QUESTIONS,
  source: NIST_SOURCE,
  sourceUrl: 'https://physics.nist.gov/PhysRefData/Handbook/element_name.htm',
  license: NIST_LICENSE,
  checkedAt: CHECKED_AT,
  method: 'manual-check-of-NIST-element-index-and-symbol',
  status: 'approved',
};
